#!/bin/bash

# Read the current version number from version.txt
VERSION=$(<version.txt)

# Increment the version number
NEW_VERSION=$((VERSION + 1))

# Update the version.txt file with the new version number
echo $NEW_VERSION > version.txt

# Add the updated version.txt to the staging area
git add version.txt

# Continue with the commit
exit 0

