name: Maven assertions

on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:
  build:

    runs-on: macOS-latest  # Use macOS runner

    steps:
     - name: Checkout code
       uses: actions/checkout@v3

     - name: Set up JDK 18
       uses: actions/setup-java@v3
       with:
        java-version: '18'
        distribution: 'temurin'
        cache: 'maven'

     - name: Build and Test
       run: mvn clean verify  --file root/pom.xml

    # - name: Code Quality Analysis
    #   run: mvn sonar:sonar

     - name: Check Code Coverage
       run: mvn clean site:site site:stage scm-publish:publish-scm
 
