name: Maven site + site:stage + scm-publish

on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:
  build:

    runs-on: macOS-latest  # Use macOS runner

    steps:
     - name: Checkout code
       uses: actions/checkout@v3

     - name: Set up JDK 18
       uses: actions/setup-java@v3
       with:
        java-version: '18'
        distribution: 'temurin'
        cache: 'maven'
        
     - name: Set up Git
       run: |
          git config --global user.email "munoabr8@gmail.com"
          git config --global user.name "munoabr8"
          git config --global credential.helper 'store --file ~/.git-credentials'
          echo "https://github.com:${{ secrets.GH_PAT }}" > ~/.git-credentials


     - name: Publishing page
       run: mvn clean site:site site:stage scm-publish:publish-scm -f root/pom.xml
 
