name: Maven SCM List of project files

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Get list of projects using SCM 
        run: mvn scm:status --file root/pom.xml
        
 
