name: Code Analysis

on:
  push:
    branches:
      - main

jobs:
  code-analysis:
    runs-on: macos-latest

    steps:
 
      
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: maven
               
      - name: Check out code and Run Checkstyle
        uses: actions/checkout@v3
          with:ref:main
         run >
           mvn -B package --file root/pom.xml
           mvn checkstyle:check
