name: Code Analysis

on:
  push:
    branches:
      - main

jobs:
  code-analysis:
    runs-on: macos-latest

    steps:

     - name: Check out code
       uses: actions/checkout@v3
       with:
        ref: main  # or specify the branch or tag you want to check out

      
     - name: Set up JDK 18
       uses: actions/setup-java@v3
       with:
          java-version: '18'
          distribution: 'temurin'
          cache: maven
               
 
     - name: Run Checkstyle
       run: |
          mvn -B package --file root/pom.xml
          mvn checkstyle:check
