name: Maven site + site:stage + javadoc + scm-publish

on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:
  build:

    runs-on: macOS-latest  # Use macOS runner

    env:
      GH_PAT: ${{ secrets.GH_PAT }}

    steps:
     - name: Checkout code
       uses: actions/checkout@v3

     - name: Set up JDK 18
       uses: actions/setup-java@v3
       with:
        java-version: '18'
        distribution: 'temurin'
        cache: 'maven'
  
     - name: Set up "hub" Configuration
       run: |
        hub api user        
