name: Testing Publish Plugin  

on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:
  build:

    runs-on: macOS-latest  # Use macOS runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 18
      uses: actions/setup-java@v2
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: 'maven'


    - name: Build, site,stage publish  with Maven
      run: mvn -B clean package --file root/pom.xml

